name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
      
    - name: Setup Go
      uses: actions/setup-go@v4

    - name: build
      run: make platform-all

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/esbuild-*
